
// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: my.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
using System.Text;

namespace celerity.visualizer.tracedata.rawtrace
{

	[global::ProtoBuf.ProtoContract()]
	public partial class Dependency : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			=> global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

		[global::ProtoBuf.ProtoMember(1, Name = @"id")]
		public ulong Id { get; set; }

		[global::ProtoBuf.ProtoMember(2, Name = @"kind")]
		public DependencyKind Kind { get; set; }

		public string ToString(int indentLevel)
		{
			return new string(' ', indentLevel * 4) + "Id: " + Id + ", DependencyKind: " + Kind;

		}
	}

	[global::ProtoBuf.ProtoContract()]
	public partial class Box3D : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			=> global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

		[global::ProtoBuf.ProtoMember(1, Name = @"min0")]
		public ulong Min0 { get; set; }

		[global::ProtoBuf.ProtoMember(2, Name = @"min1")]
		public ulong Min1 { get; set; }

		[global::ProtoBuf.ProtoMember(3, Name = @"min2")]
		public ulong Min2 { get; set; }

		[global::ProtoBuf.ProtoMember(4, Name = @"max0")]
		public ulong Max0 { get; set; }

		[global::ProtoBuf.ProtoMember(5, Name = @"max1")]
		public ulong Max1 { get; set; }

		[global::ProtoBuf.ProtoMember(6, Name = @"max2")]
		public ulong Max2 { get; set; }

		public override string ToString()
		{
			return "Min0: " + Min0 + ", Min1: " + Min1 + ", Min2: " + Min2 + ", Max0: " + Max0 + ", Max1: " + Max1 + ", Max2: " + Max2;
		}

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class BufferAccess : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			=> global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

		[global::ProtoBuf.ProtoMember(1, Name = @"buffer_id")]
		public ulong BufferId { get; set; }

		[global::ProtoBuf.ProtoMember(2, Name = @"range")]
		public Box3D Range { get; set; }

		[global::ProtoBuf.ProtoMember(3, Name = @"mode")]
		public AccessMode Mode { get; set; }

		public string ToString(int indentLevel)
		{
			return new string(' ', indentLevel * 4) + "BufferId: " + BufferId + ", Range: [" + Range + "], AccessMode: " + Mode;
		}

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class Task : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			=> global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

		[global::ProtoBuf.ProtoMember(1, Name = @"id")]
		public ulong Id { get; set; }

		[global::ProtoBuf.ProtoMember(2, Name = @"target")]
		public ExecutionTarget Target { get; set; }

		[global::ProtoBuf.ProtoMember(3, Name = @"name")]
		[global::System.ComponentModel.DefaultValue("")]
		public string Name { get; set; } = "";

		[global::ProtoBuf.ProtoMember(4, Name = @"predecessors")]
		public global::System.Collections.Generic.List<Dependency> Predecessors { get; } = new global::System.Collections.Generic.List<Dependency>();

		public string ToString(int indentLevel)
		{
			StringBuilder builder = new();
			builder.Append(new string(' ', indentLevel * 4) + "Id " + Id + ", ExecutionTarget " + Target + ", Name: " + Name + ", Predecessors: [");
			foreach (Dependency dependency in Predecessors)
			{
				builder.Append("\n" + dependency.ToString(indentLevel + 1) + ",");
			}
			builder.Append("]");

			return builder.ToString();
		}

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class Command : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			=> global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

		[global::ProtoBuf.ProtoMember(1, Name = @"id")]
		public ulong Id { get; set; }

		[global::ProtoBuf.ProtoMember(2, Name = @"node_id")]
		public ulong NodeId { get; set; }

		[global::ProtoBuf.ProtoMember(3, Name = @"type")]
		public CommandType Type { get; set; }

		[global::ProtoBuf.ProtoMember(4, Name = @"task_id")]
		public ulong TaskId { get; set; }

		[global::ProtoBuf.ProtoMember(5, Name = @"execution_range")]
		public Box3D ExecutionRange { get; set; }

		[global::ProtoBuf.ProtoMember(6, Name = @"other_node_id")]
		public ulong OtherNodeId { get; set; }

		[global::ProtoBuf.ProtoMember(7, Name = @"buffer_accesses")]
		public global::System.Collections.Generic.List<BufferAccess> BufferAccesses { get; } = new global::System.Collections.Generic.List<BufferAccess>();

		[global::ProtoBuf.ProtoMember(8, Name = @"predecessors")]
		public global::System.Collections.Generic.List<Dependency> Predecessors { get; } = new global::System.Collections.Generic.List<Dependency>();

		public string ToString(int indentLevel)
		{
			StringBuilder builder = new();
			builder.Append(new string(' ', indentLevel * 4) + "Id: " + Id + ", NodeId: " + NodeId + ", CommandType: " + Type + ", TaskId: " + TaskId + ", ExecutionRange: [" + ExecutionRange + "], OtherNodeId: " + OtherNodeId + ", BufferAccesses: [");

			foreach (BufferAccess bufferAccesses in BufferAccesses)
			{
				builder.Append("\n" + bufferAccesses.ToString(indentLevel + 1) + ",");
			}
			builder.Append("],\n" + new string(' ', indentLevel * 4) + "Predecessors: [");
			foreach (Dependency dependency in Predecessors)
			{
				builder.Append("\n" + dependency.ToString(indentLevel + 1) + ",");
			}
			builder.Append("]");

			return builder.ToString();
		}

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class PollingStats : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			=> global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

		[global::ProtoBuf.ProtoMember(1, Name = @"min")]
		public ulong Min { get; set; }

		[global::ProtoBuf.ProtoMember(2, Name = @"max")]
		public ulong Max { get; set; }

		[global::ProtoBuf.ProtoMember(3, Name = @"avg")]
		public ulong Avg { get; set; }

		[global::ProtoBuf.ProtoMember(4, Name = @"num_samples")]
		public ulong NumSamples { get; set; }

		public override string ToString()
		{
			return "Min: " + Min + ", Max: " + Max + ", Avg: " + Avg + ", NumSamples: " + NumSamples;
		}

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class Job : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			=> global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

		[global::ProtoBuf.ProtoMember(1, Name = @"command_id")]
		public ulong CommandId { get; set; }

		[global::ProtoBuf.ProtoMember(2, Name = @"started_at")]
		public ulong StartedAt { get; set; }

		[global::ProtoBuf.ProtoMember(3, Name = @"finished_at")]
		public ulong FinishedAt { get; set; }

		[global::ProtoBuf.ProtoMember(4, Name = @"polling_stats")]
		public PollingStats PollingStats { get; set; }

		public string ToString(int indentLevel)
		{
			return new string(' ', indentLevel * 4) + "CommandId: " + CommandId + ", StartedAt: " + StartedAt + ", FinishedAt: " + FinishedAt + ", (Took: " + (FinishedAt - StartedAt) + "), PollingStats: [" + PollingStats.ToString() + "]";
		}

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class RunInfo : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			=> global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

		[global::ProtoBuf.ProtoMember(1, Name = @"reference_time_point")]
		public ulong ReferenceTimePoint { get; set; }

		[global::ProtoBuf.ProtoMember(2, Name = @"executable_name")]
		[global::System.ComponentModel.DefaultValue("")]
		public string ExecutableName { get; set; } = "";

		[global::ProtoBuf.ProtoMember(3, Name = @"executable_args")]
		public global::System.Collections.Generic.List<string> ExecutableArgs { get; } = new global::System.Collections.Generic.List<string>();

		public override string ToString()
		{
			return "ReferenceTimePoint: " + ReferenceTimePoint + ", ExecutableName: " + ExecutableName + ", ExecutableArgs: [" + string.Join(",", ExecutableArgs?.ToArray() ?? (new string[] { "" })) + "]";
		}

	}

	[global::ProtoBuf.ProtoContract()]
	public partial class TracePayload : global::ProtoBuf.IExtensible
	{
		private global::ProtoBuf.IExtension __pbn__extensionData;
		global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
			=> global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

		[global::ProtoBuf.ProtoMember(1, Name = @"version")]
		public ulong Version { get; set; }

		[global::ProtoBuf.ProtoMember(2, Name = @"run_id")]
		[global::System.ComponentModel.DefaultValue("")]
		public string RunId { get; set; } = "";

		[global::ProtoBuf.ProtoMember(3, Name = @"run_info")]
		public RunInfo RunInfo { get; set; }

		[global::ProtoBuf.ProtoMember(4, Name = @"jobs")]
		public global::System.Collections.Generic.List<Job> Jobs { get; } = new global::System.Collections.Generic.List<Job>();

		[global::ProtoBuf.ProtoMember(5, Name = @"tasks")]
		public global::System.Collections.Generic.List<Task> Tasks { get; } = new global::System.Collections.Generic.List<Task>();

		[global::ProtoBuf.ProtoMember(6, Name = @"commands")]
		public global::System.Collections.Generic.List<Command> Commands { get; } = new global::System.Collections.Generic.List<Command>();

		[global::ProtoBuf.ProtoMember(7, Name = @"source_node_id")]
		public ulong SourceNodeId { get; set; }

		[global::ProtoBuf.ProtoMember(8, Name = @"is_final_payload")]
		public bool IsFinalPayload { get; set; }

		public override string ToString()
		{
			StringBuilder builder = new();
			builder.Append("Version " + Version + ", RunId " + RunId + ", RunInfo [" + (RunInfo?.ToString() ?? "[NONE FOUND]") + "], Jobs: [");

			int indentLevel = 1;

			foreach (Job job in Jobs)
			{
				builder.Append("\n" + job.ToString(indentLevel) + ",");
			}
			builder.Append("],\nTasks: [");
			foreach (Task task in Tasks)
			{
				builder.Append("\n" + task.ToString(indentLevel) + ",");
			}
			builder.Append("],\nCommands: [");
			foreach (Command command in Commands)
			{
				builder.Append("\n" + command.ToString(indentLevel) + ",");
			}
			builder.Append("],\nSourceNodeId: " + SourceNodeId + ", IsFinalPayload: " + IsFinalPayload);

			return builder.ToString();
		}
	}

	[global::ProtoBuf.ProtoContract()]
	public enum DependencyKind
	{
		[global::ProtoBuf.ProtoEnum(Name = @"ANTI_DEP")]
		AntiDep = 0,
		[global::ProtoBuf.ProtoEnum(Name = @"ORDER_DEP")]
		OrderDep = 1,
		[global::ProtoBuf.ProtoEnum(Name = @"TRUE_DEP")]
		TrueDep = 2,
	}

	[global::ProtoBuf.ProtoContract()]
	public enum AccessMode
	{
		[global::ProtoBuf.ProtoEnum(Name = @"READ")]
		Read = 0,
		[global::ProtoBuf.ProtoEnum(Name = @"WRITE")]
		Write = 1,
		[global::ProtoBuf.ProtoEnum(Name = @"READ_WRITE")]
		ReadWrite = 2,
		[global::ProtoBuf.ProtoEnum(Name = @"DISCARD_WRITE")]
		DiscardWrite = 3,
		[global::ProtoBuf.ProtoEnum(Name = @"DISCARD_READ_WRITE")]
		DiscardReadWrite = 4,
		[global::ProtoBuf.ProtoEnum(Name = @"ATOMIC")]
		Atomic = 5,
	}

	[global::ProtoBuf.ProtoContract()]
	public enum ExecutionTarget
	{
		[global::ProtoBuf.ProtoEnum(Name = @"DEVICE")]
		Device = 0,
		[global::ProtoBuf.ProtoEnum(Name = @"HOST")]
		Host = 1,
		[global::ProtoBuf.ProtoEnum(Name = @"NONE")]
		None = 2,
	}

	[global::ProtoBuf.ProtoContract()]
	public enum CommandType
	{
		[global::ProtoBuf.ProtoEnum(Name = @"NOP")]
		Nop = 0,
		[global::ProtoBuf.ProtoEnum(Name = @"HORIZON")]
		Horizon = 1,
		[global::ProtoBuf.ProtoEnum(Name = @"TASK")]
		Task = 2,
		[global::ProtoBuf.ProtoEnum(Name = @"PUSH")]
		Push = 3,
		[global::ProtoBuf.ProtoEnum(Name = @"AWAIT_PUSH")]
		AwaitPush = 4,
		[global::ProtoBuf.ProtoEnum(Name = @"SHUTDOWN")]
		Shutdown = 5,
		[global::ProtoBuf.ProtoEnum(Name = @"SYNC")]
		Sync = 6,
	}

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
